package nordis.nordisquiz

class PlayerNameCreator {
    fun womenCreator(){
        nameWomenList.add("Александра")
        nameWomenList.add("Алена")
        nameWomenList.add("Алина")
        nameWomenList.add("Алина Смирн")
        nameWomenList.add("Алиса")
        nameWomenList.add("Алиса27")
        nameWomenList.add("Анастасия")
        nameWomenList.add("Ангелина")
        nameWomenList.add("Анна")
        nameWomenList.add("Анна Хет")
        nameWomenList.add("Арина")
        nameWomenList.add("Валерия")
        nameWomenList.add("Валерия88")
        nameWomenList.add("Варвара")
        nameWomenList.add("Василиса")
        nameWomenList.add("Вера")
        nameWomenList.add("Вера Кузн")
        nameWomenList.add("Вероника")
        nameWomenList.add("Вероника79")
        nameWomenList.add("Виктория")
        nameWomenList.add("Виктория Зю")
        nameWomenList.add("Дарья")
        nameWomenList.add("Диана")
        nameWomenList.add("Ева")
        nameWomenList.add("Ева89")
        nameWomenList.add("Евгения")
        nameWomenList.add("Екатерина")
        nameWomenList.add("Елена")
        nameWomenList.add("Елена85")
        nameWomenList.add("Елизавета")
        nameWomenList.add("Злата")
        nameWomenList.add("Ирина")
        nameWomenList.add("Карина")
        nameWomenList.add("Карина91")
        nameWomenList.add("Кира")
        nameWomenList.add("Кристина")
        nameWomenList.add("Ксения")
        nameWomenList.add("Ксения69")
        nameWomenList.add("Лилия")
        nameWomenList.add("Любовь")
        nameWomenList.add("Людмила")
        nameWomenList.add("Маргарита")
        nameWomenList.add("Марина")
        nameWomenList.add("Марин Кисель")
        nameWomenList.add("Мария")
        nameWomenList.add("Мария Изо")
        nameWomenList.add("Милана")
        nameWomenList.add("Надежда")
        nameWomenList.add("Наталья")
        nameWomenList.add("Ольга")
        nameWomenList.add("Полина")
        nameWomenList.add("Полина Кудр")
        nameWomenList.add("Светлана")
        nameWomenList.add("София")
        nameWomenList.add("Таисия")
        nameWomenList.add("Таисия Милан")
        nameWomenList.add("Ульяна")
        nameWomenList.add("Юлия")
        nameWomenList.add("Яна")
        nameWomenList.add("Яна Бодр")
        nameWomenList.add("3a6aBHa9I")
        nameWomenList.add("DerЗykaя")
        nameWomenList.add("Кошка Рыж")
        nameWomenList.add("Pusi4ka")
        nameWomenList.add("ElenaShkk")
        nameWomenList.add("Kozadereza")
        nameWomenList.add("Panterka")
        nameWomenList.add("Rondo")
        nameWomenList.add("Грешная")
        nameWomenList.add("ЛафФфонька")
        nameWomenList.add("Юляшка я")
        nameWomenList.add("GORDAYA")
        nameWomenList.add("ICE QUEEN")
        nameWomenList.add("Women")
        nameWomenList.add("баба яга")
        nameWomenList.add("Именинница")
        nameWomenList.add("Мuлαшкα")
        nameWomenList.add("Rose")
        nameWomenList.add("ZмеючKа")
        nameWomenList.add("Анита")
        nameWomenList.add("dreamy_girl")
        nameWomenList.add("кYдРяШкА")
        nameWomenList.add("Дикая Пант")
        nameWomenList.add("mama mia")
        nameWomenList.add("Акира")
        nameWomenList.add("Yolka")
        nameWomenList.add("КаПрИзНаЯ")
        nameWomenList.add("Mini_Chery")
        nameWomenList.add("РесНичКи")
        nameWomenList.add("XSecretka")
        nameWomenList.add("Львица")
        nameWomenList.add("Незнакомка")
        nameWomenList.add("Злая_Бабуля")
        nameWomenList.add("ПоФиГиСТКa")
        nameWomenList.add("Aristokratka")
        nameWomenList.add("Брюнеточка")
        nameWomenList.add("Маляфка")
        nameWomenList.add("Конфетк@")
        nameWomenList.add("seksistar")
        nameWomenList.add("Юля МанГО")
        nameWomenList.add("LOGIKA")
        nameWomenList.add("Ксюю")
        nameWomenList.add("AMHe3u9I")
        nameWomenList.add("Амстер-ДамкА")
        nameWomenList.add("Апельсинка")
        nameWomenList.add("Лядышка")
        nameWomenList.add("Снежинка")
        nameWomenList.shuffle()

    }
    fun menCreator() {
        if (nameMenList.isEmpty()) {
            nameMenList.add("Александр")
            nameMenList.add("Алексей")
            nameMenList.add("Андрей")
            nameMenList.add("Антон")
            nameMenList.add("Арсений")
            nameMenList.add("Артем")
            nameMenList.add("Василий")
            nameMenList.add("Василий")
            nameMenList.add("Виктор")
            nameMenList.add("Виталий")
            nameMenList.add("Владимир")
            nameMenList.add("Владислав")
            nameMenList.add("Вячеслав")
            nameMenList.add("Георгий")
            nameMenList.add("Глеб")
            nameMenList.add("Давид")
            nameMenList.add("Даниил")
            nameMenList.add("Денис")
            nameMenList.add("Дмитрий")
            nameMenList.add("Евгений")
            nameMenList.add("Егор")
            nameMenList.add("Иван")
            nameMenList.add("Игорь")
            nameMenList.add("Илья")
            nameMenList.add("Кирилл")
            nameMenList.add("Константин")
            nameMenList.add("Лев")
            nameMenList.add("Максим")
            nameMenList.add("Марк")
            nameMenList.add("Матвей")
            nameMenList.add("Михаил")
            nameMenList.add("Никита")
            nameMenList.add("Николай")
            nameMenList.add("Олег")
            nameMenList.add("Павел")
            nameMenList.add("Роман")
            nameMenList.add("Руслан")
            nameMenList.add("Сергей")
            nameMenList.add("Станислав")
            nameMenList.add("Степан")
            nameMenList.add("Тимофей")
            nameMenList.add("Тимур")
            nameMenList.add("Федор")
            nameMenList.add("Юрий")
            nameMenList.add("Ярослав")
            nameMenList.add("Rezak")
            nameMenList.add("Странник")
            nameMenList.add("Mr.Nobody")
            nameMenList.add("The Brain")
            nameMenList.add("Mexanuk")
            nameMenList.add("DeadMan")
            nameMenList.add("Джон Уик")
            nameMenList.add("Купидон")
            nameMenList.add("Химик")
            nameMenList.add("Князь")
            nameMenList.add("patriot")
            nameMenList.add("AlKaSh")
            nameMenList.add("CrazzyMan")
            nameMenList.add("Gamunkul")
            nameMenList.add("Jayson")
            nameMenList.add("Joe Balance")
            nameMenList.add("Mr.Panda")
            nameMenList.add("Nod51")
            nameMenList.add("Stalin")
            nameMenList.add("VALERIY07")
            nameMenList.add("Uncle77Sam")
            nameMenList.add("UTheBaron")
            nameMenList.add("IGOR4IK388")
            nameMenList.add("Glebas-GoI")
            nameMenList.add("BarclaYsu")
            nameMenList.add("гризли")
            nameMenList.add("xxxx")
            nameMenList.add("PROFESOR")
            nameMenList.add("sladkий")
            nameMenList.add("BazArov71")
            nameMenList.add("УмнИк21")
            nameMenList.add("Победитель")
            nameMenList.add("Карл!")
            nameMenList.add("WTF")
            nameMenList.add("Пророк")
            nameMenList.add("Самец94")
            nameMenList.add("DRAKON")
            nameMenList.add("Makarov")
            nameMenList.add("ТУгОй")
            nameMenList.add("Демон Ночи")
            nameMenList.add("Уровнитель")
            nameMenList.add("Сенпай")
            nameMenList.add("ДядяГугл")
            nameMenList.add("БУЛьДоЗеР")
            nameMenList.add("Голубь")
            nameMenList.add("УслИк")
            nameMenList.add("Фантом")
            nameMenList.add(".Л.е.ш.и.й.")
            nameMenList.add("iron warrior")
            nameMenList.add("Nameless")
            nameMenList.add("ROBOT")
            nameMenList.add("f0rest")
            nameMenList.add("Morder")
            nameMenList.add("KilLeRRcooL")
            nameMenList.add("FireBOY")
            nameMenList.add("Strange Pilot")
            nameMenList.add("Naruto")
            nameMenList.add("Patrik17")
            nameMenList.add("Patriot257")
            nameMenList.add("Patriot257")
            nameMenList.add("ГУСЬ")
            nameMenList.add("Madis")
            nameMenList.add("Matrix")
            nameMenList.add("Martin")
            nameMenList.add("Martin")
            nameMenList.add("Джеймс Клерк")
            nameMenList.add("Галилео")
            nameMenList.add("Эйнштейн")
            nameMenList.add("Линус Карл")
            nameMenList.add("Дарвин")
            nameMenList.add("Го_Си")
            nameMenList.add("Мазаччо")
            nameMenList.shuffle()
        }
    }
    fun womenNumeresCreator(){
        numbersOfWomenList.add(1)
        numbersOfWomenList.add(2)
        numbersOfWomenList.add(3)
        numbersOfWomenList.add(6)
        numbersOfWomenList.add(8)
        numbersOfWomenList.add(9)
        numbersOfWomenList.add(12)
        numbersOfWomenList.add(14)
        numbersOfWomenList.add(16)
        numbersOfWomenList.add(18)
        numbersOfWomenList.add(20)
        numbersOfWomenList.add(22)
        numbersOfWomenList.add(24)
        numbersOfWomenList.add(26)
        numbersOfWomenList.add(28)
        numbersOfWomenList.add(29)
        numbersOfWomenList.add(30)
        numbersOfWomenList.add(32)
        numbersOfWomenList.add(34)
        numbersOfWomenList.add(36)
        numbersOfWomenList.add(38)
        numbersOfWomenList.add(40)
        numbersOfWomenList.add(42)
        numbersOfWomenList.add(44)
        numbersOfWomenList.add(45)
        numbersOfWomenList.add(46)
        numbersOfWomenList.add(48)
        numbersOfWomenList.add(49)
        numbersOfWomenList.add(50)
    }
}